enum OrderStatus {
    APPROVEMENT_AWAITING = "APPROVEMENT_AWAITING",
    DELIVERING = "DELIVERING",
    SUCCESS = "SUCCESS",
    PAYMENT_AWAITING = "PAYMENT_AWAITING",
    CANCELLED = "CANCELLED"
}
export default OrderStatus;